Models/Requests.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CapstoneBatSignal.Models
{
    public class Requests
    {
        public int Id { get; set; }
        public string StudentUserId { get; set; }

        public ApplicationUser StudentUser { get; set; }

        public string InstructorUserId { get; set; }

        public ApplicationUser InstructorUser { get; set; }
        
        public string Description { get; set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateFinished { get; set; }

        public bool IsConfirmed { get; set; }

        public bool IsTutoring { get; set; }
    }
}

Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CapstoneBatSignal.Data;
using CapstoneBatSignal.Models;
using Microsoft.AspNetCore.Identity;

namespace CapstoneBatSignal.Controllers
{
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RequestsController(ApplicationDbContext context,
                                  UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Requests
        public async Task<IActionResult> Index(string batSheet)
        {
            if (batSheet == "TutoringIsTrue")
            {                                                                                      /*where goes here where istutoring condition true*/
                var applicationDbContext = _context.Requests.Include(r => r.InstructorUser).Include(r => r.StudentUser)
                    .Where(r => r.IsTutoring == true
                                && r.IsConfirmed == false);
               //put view data here
                //leave thsi part outside of condtional
                return View(await applicationDbContext.ToListAsync());
            }
            else
            {
                var applicationDbContext = _context.Requests.Include(r => r.InstructorUser).Include(r => r.StudentUser)
                        .Where(r => r.IsTutoring == false
                                 && r.IsConfirmed == false);
                return View(await applicationDbContext.ToListAsync());
            }

            

            
            //else return same thing
        }
        
            
            //send a little piece of data to signal to let it know you want bat sheet or tutor request

            //asp- route - value [(sends little piece of data to ontroller from a tag to test conditional)

            //first thing - breakpoint line 31, string of batsignal or tutoring, make sure its two different pieces of data.

            //look up  .where - depednint on batsheet param, FormatFilterAttribute out just turoring or batsheet



        

        // GET: Requests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requests = await _context.Requests
                .Include(r => r.InstructorUser)
                .Include(r => r.StudentUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (requests == null)
            {
                return NotFound();
            }

            return View(requests);
        }

        // GET: Requests/Create
        public IActionResult Create()
        {
            
            ViewData["InstructorUserId"] = new SelectList(_context.User, "Id", "Id");
            ViewData["StudentUserId"] = new SelectList(_context.User, "Id", "Id");
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentUserId,InstructorUserId,Description,DateCreated,DateFinished,IsConfirmed,IsTutoring")] Requests requests)
        {
            ModelState.Remove("requests.InstructorUserId");
            ModelState.Remove("requests.StudentUserId");
            ModelState.Remove("requests.UserId");
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                requests.StudentUserId = user.Id;
                _context.Add(requests);
                await _context.SaveChangesAsync();
                if (requests.IsTutoring == true)
                {
                    return RedirectToAction("Index", new { batSheet = "TutoringIsTrue" });
                }
                return RedirectToAction(nameof(Index));
                /*going to have to redirect if batSignal = true*/
            }

            ViewData["InstructorUserId"] = new SelectList(_context.User, "Id", "Id", requests.InstructorUserId);
            ViewData["StudentUserId"] = new SelectList(_context.User, "Id", "Id", requests.StudentUserId);
            return View(requests);
        }

        // GET: Requests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requests = await _context.Requests.FindAsync(id);
            if (requests == null)
            {
                return NotFound();
            }
            ViewData["InstructorUserId"] = new SelectList(_context.User, "Id", "Id", requests.InstructorUserId);
            ViewData["StudentUserId"] = new SelectList(_context.User, "Id", "Id", requests.StudentUserId);
            return View(requests);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentUserId,InstructorUserId,Description,DateCreated,DateFinished,IsConfirmed,IsTutoring")] Requests requests)
        {
            if (id != requests.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(requests);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestsExists(requests.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InstructorUserId"] = new SelectList(_context.User, "Id", "Id", requests.InstructorUserId);
            ViewData["StudentUserId"] = new SelectList(_context.User, "Id", "Id", requests.StudentUserId);
            return View(requests);
        }

        // GET: Requests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var requests = await _context.Requests
                .Include(r => r.InstructorUser)
                .Include(r => r.StudentUser)
                .FirstOrDefaultAsync(m => m.Id == id);

            //if (requests == null)
            //{
            //    return NotFound();
            //}
            //try
            //{
            //    _context.Requests.Remove(requests);
            //    await _context.SaveChangesAsync();
            //}
            //catch (Exception) when (requests.IsConfirmed == false)
            //{
                requests.IsConfirmed = true;
                _context.Update(requests);
                await _context.SaveChangesAsync();
            if (requests.IsTutoring == true)
            {
                return RedirectToAction("Index", new { batSheet = "TutoringIsTrue" });
            }
            return RedirectToAction(nameof(Index));

            return RedirectToAction(nameof(Index));
        }
        
    //        return View(requests);
    //}

    //POST: Requests/Delete/5
    [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var requests = await _context.Requests.FindAsync(id);
            _context.Requests.Remove(requests);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestsExists(int id)
        {
            return _context.Requests.Any(e => e.Id == id);
        }
    }
}

Views/Requests/Create.cshtml
@model CapstoneBatSignal.Models.Requests

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Requests</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
 
 
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsTutoring" /> Tutoring Request?
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Requests/Delete.cshtml
@model CapstoneBatSignal.Models.Requests

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Requests</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentUser.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstructorUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstructorUser.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFinished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFinished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsConfirmed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsConfirmed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsTutoring)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsTutoring)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Requests/Details.cshtml
@model CapstoneBatSignal.Models.Requests

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Requests</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentUser.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InstructorUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InstructorUser.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFinished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFinished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsConfirmed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsConfirmed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsTutoring)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsTutoring)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Requests/Edit.cshtml
@model CapstoneBatSignal.Models.Requests

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Requests</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StudentUserId" class="control-label"></label>
                <select asp-for="StudentUserId" class="form-control" asp-items="ViewBag.StudentUserId"></select>
                <span asp-validation-for="StudentUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstructorUserId" class="control-label"></label>
                <select asp-for="InstructorUserId" class="form-control" asp-items="ViewBag.InstructorUserId"></select>
                <span asp-validation-for="InstructorUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFinished" class="control-label"></label>
                <input asp-for="DateFinished" class="form-control" />
                <span asp-validation-for="DateFinished" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsConfirmed" /> @Html.DisplayNameFor(model => model.IsConfirmed)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsTutoring" /> @Html.DisplayNameFor(model => model.IsTutoring)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Requests/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using CapstoneBatSignal.Models;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@model IEnumerable<CapstoneBatSignal.Models.Requests>

@{
    ViewData["Title"] = "Index";
}
@if (UserManager.GetUserAsync(User).Result.IsInstructor == false)
    //View data
{
    <h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                Student Name
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>



            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentUser.FirstName) @Html.DisplayFor(modelItem => item.StudentUser.LastName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>

            @if (UserManager.GetUserAsync(User).Result.IsInstructor == true)
            {
        <td>
            
            <div class=" form-group">
                

                  
                      <a asp-controller="Requests" asp-action="Delete" asp-route-id="@item.Id"  > 
                       <button type="button" class="btn btn-primary">Completed</button>
                    </a>
                    <span asp-validation-for="@item.IsConfirmed" class="text-danger"></span>
                
            </div>
            
            </td>
            }

            @*put in a tags to send to controller*@




<td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                @*<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|*@
                
            </td>
        </tr>
        }
    </tbody>
</table>